### ISSUE TITLE
添加好友的itchat.add_friend找不到

### ISSUE THREAD

**Issue by Chiaki-Chan** [why2lyj/ItChat-UOS#23]
在提交前，请确保您已经检查了以下内容!

- [ ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [x] 我已经阅读并按[文档][document] 中的指引进行了操作
- [x] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [x] 本问题确实关于`itchat`, 而不是其他项目.
- [x] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/itchat/components/register.py", line 60, in configured_reply
    r = replyFn(msg)
  File "/Volumes/Data/Code/Haoyuan/ChatGPT/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 34, in add_friend
    itchat.add_friend(**msg['Text'])
  File "/usr/local/lib/python3.9/site-packages/itchat/storage/templates.py", line 158, in verify
    return self.core.add_friend(**self.verifyDict)
AttributeError: 'Core' object has no attribute 'add_friend'
```

您的itchat版本为：`1.5.0.dev`。

其他的内容或者问题更详细的描述都可以添加在下面：

> [您的内容]

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by dfldylan** [comment]
改成accept_friend了

**Comment by lmmsoft** [comment]
> 改成accept_friend了

itchat.accept_friend(username, v4) 的参数v4怎么传呀？看了下代码里的文档还是旧的，没有更新

**Comment by lmmsoft** [comment]
> accept_friend

搞定了，
> ticket_v4 = msg['RecommendInfo']['Ticket']

**Comment by dfldylan** [comment]
> > accept_friend
> 
> 搞定了，
> 
> > ticket_v4 = msg['RecommendInfo']['Ticket']

可以正常同意好友申请了？

**Comment by lmmsoft** [comment]
> > > accept_friend
> > 
> > 
> > 搞定了，
> > > ticket_v4 = msg['RecommendInfo']['Ticket']
> 
> 可以正常同意好友申请了？

是的，使用 itchat.accept_friend(username, msg['RecommendInfo']['Ticket'])  可以通过群聊加好友的，但是通过分享名片添加还不行

**Comment by limcod** [comment]
你好请问这个msg['RecommendInfo']['Ticket']指的是什么  我改如何修改相关的代码才能使其可以使用

**Comment by jinde98** [comment]
> > > > accept_friend
> > > 
> > > 
> > > 搞定了，
> > > > ticket_v4 = msg['RecommendInfo']['Ticket']
> > 
> > 
> > 可以正常同意好友申请了？
> 
> 是的，使用 itchat.accept_friend(username, msg['RecommendInfo']['Ticket']) 可以通过群聊加好友的，但是通过分享名片添加还不行

我没看明白啊，我用的代码是

@itchat.msg_register(FRIENDS)
def add_friend(msg):
print(msg)
msg.user.verify()
msg.user.send('很高兴认识你')
出错提示如下：
File "/home/jd/.local/lib/python3.10/site-packages/itchat/components/register.py", line 60, in configured_reply
r = replyFn(msg)
File "/home/jd/wechat/wechatbot.py", line 57, in add_friend
msg.user.verify()
File "/home/jd/.local/lib/python3.10/site-packages/itchat/storage/templates.py", line 158, in verify
return self.core.add_friend(**self.verifyDict)
AttributeError: 'Core' object has no attribute 'add_friend'. Did you mean: 'get_friends'?
说没有add_friend 这个属性

**Comment by limcod** [comment]
> > > > > accept_friend
> > > > 
> > > > 
> > > > 搞定了，
> > > > > ticket_v4 = msg['推荐信息']['工单']
> > > 
> > > 
> > > 可以正常同意好友申请了？
> > 
> > 
> > 是的，使用 itchat.accept_friend（username， msg['RecommendInfo']['Ticket']） 可以通过群聊加好友的，但是通过分享名片添加还不行
> 
> 我没看明白啊，我用的代码是
> 
> @itchat.msg_register（FRIENDS） def add_friend（msg）： print（msg） msg.user.verify（） msg.user.send（'很高兴认识你'） 出错提示如下： 文件 “/home/jd/.local/lib/python3.10/site-packages/itchat/components/register.py”，第 60 行，在 configured_reply r = replyFn（msg） 中 文件“/home/jd/wechat/wechatbot.py”，第 57 行，在 msg.user.verify（） add_friend 中文件“/home/jd/.local/lib/python3.10/site-packages/itchat/storage/templates.py”，第 158 行，在 verify 返回 self.core.add_friend（**self.verifyDict） AttributeError：“Core”对象没有属性“add_friend”。你的意思是：“get_friends”吗？ 说没有add_friend 这个属性

上面说 add_friend 改成 accept_friend了

**Comment by limcod** [comment]
> > > > accept_friend
> > > 
> > > 
> > > 搞定了，
> > > > ticket_v4 = msg['RecommendInfo']['Ticket']
> > 
> > 
> > 可以正常同意好友申请了？
> 
> 是的，使用 itchat.accept_friend(username, msg['RecommendInfo']['Ticket']) 可以通过群聊加好友的，但是通过分享名片添加还不行


msg['RecommendInfo']['Ticket']应该怎么获取  或者说源码里面应该怎么改

**Comment by limcod** [comment]
> > > > > accept_friend
> > > > 
> > > > 
> > > > 搞定了，
> > > > > ticket_v4 = msg['RecommendInfo']['Ticket']
> > > 
> > > 
> > > 可以正常同意好友申请了？
> > 
> > 
> > 是的，使用 itchat.accept_friend(username, msg['RecommendInfo']['Ticket']) 可以通过群聊加好友的，但是通过分享名片添加还不行
> 
> msg['RecommendInfo']['Ticket']应该怎么获取 或者说源码里面应该怎么改

我明白了 但是当我把accept_friend接口中的Opcode参数改为2 时不能调通   是目前版本的协议不支持该功能吗  还是说需要修改其他的参数

**Comment by jinde98** [comment]
> > > > > > accept_friend
> > > > > 
> > > > > 
> > > > > 搞定了，
> > > > > > ticket_v4 = msg['RecommendInfo']['Ticket']
> > > > 
> > > > 
> > > > 可以正常同意好友申请了？
> > > 
> > > 
> > > 是的，使用 itchat.accept_friend(username, msg['RecommendInfo']['Ticket']) 可以通过群聊加好友的，但是通过分享名片添加还不行
> > 
> > 
> > msg['RecommendInfo']['Ticket']应该怎么获取 或者说源码里面应该怎么改
> 
> 我明白了 但是当我把accept_friend接口中的Opcode参数改为2 时不能调通 是目前版本的协议不支持该功能吗 还是说需要修改其他的参数

确认后如何自动添加对方为好友？

**Comment by CodeSnailss** [comment]
> > > > > > > accept_friend
> > > > > > 
> > > > > > 
> > > > > > 搞定了，
> > > > > > > ticket_v4 = msg['RecommendInfo']['Ticket']
> > > > > 
> > > > > 
> > > > > 可以正常同意好友申请了？
> > > > 
> > > > 
> > > > 是的，使用 itchat.accept_friend(username, msg['RecommendInfo']['Ticket']) 可以通过群聊加好友的，但是通过分享名片添加还不行
> > > 
> > > 
> > > msg['RecommendInfo']['Ticket']应该怎么获取 或者说源码里面应该怎么改
> > 
> > 
> > 我明白了 但是当我把accept_friend接口中的Opcode参数改为2 时不能调通 是目前版本的协议不支持该功能吗 还是说需要修改其他的参数
> 
> 确认后如何自动添加对方为好友？

这个你要研究一下消息体也就是你的msg的格式，一般来说刚刚通过验证的好友里面UserName一般在RecommendInfo里面
所以你的代码可以改成类似于下面这样：
@itchat.msg_register(FRIENDS)
def add_friend(msg):
    print(msg)
    itchat.accept_friend(msg['RecommendInfo']['UserName'], msg['RecommendInfo']['Ticket'])
    print("成功通过验证信息")

**Comment by jinde98** [comment]
> > > > > > > > accept_friend
> > > > > > > 
> > > > > > > 
> > > > > > > 搞定了，
> > > > > > > > ticket_v4 = msg['RecommendInfo']['Ticket']
> > > > > > 
> > > > > > 
> > > > > > 可以正常同意好友申请了？
> > > > > 
> > > > > 
> > > > > 是的，使用 itchat.accept_friend(username, msg['RecommendInfo']['Ticket']) 可以通过群聊加好友的，但是通过分享名片添加还不行
> > > > 
> > > > 
> > > > msg['RecommendInfo']['Ticket']应该怎么获取 或者说源码里面应该怎么改
> > > 
> > > 
> > > 我明白了 但是当我把accept_friend接口中的Opcode参数改为2 时不能调通 是目前版本的协议不支持该功能吗 还是说需要修改其他的参数
> > 
> > 
> > 确认后如何自动添加对方为好友？
> 
> 这个你要研究一下消息体也就是你的msg的格式，一般来说刚刚通过验证的好友里面UserName一般在RecommendInfo里面 所以你的代码可以改成类似于下面这样： @itchat.msg_register(FRIENDS) def add_friend(msg): print(msg) itchat.accept_friend(msg['RecommendInfo']['UserName'], msg['RecommendInfo']['Ticket']) print("成功通过验证信息")

感谢了
