### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by code-agree** [why2lyj/ItChat-UOS#31]
在提交前，请确保您已经检查了以下内容!

- [x] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [x] 我已经阅读并按[文档][document] 中的指引进行了操作
- [x] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [x] 本问题确实关于`itchat`, 而不是其他项目.
- [x] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
Traceback (most recent call last):
  File "/root/WechatForwardBot/main.py", line 22, in <module>
    itchat.auto_login(True)
  File "/usr/local/lib/python3.11/dist-packages/itchat_uos-1.5.0.dev0-py3.11.egg/itchat/components/register.py", line 31, in auto_login
  File "/usr/local/lib/python3.11/dist-packages/itchat_uos-1.5.0.dev0-py3.11.egg/itchat/components/login.py", line 60, in login
  File "/usr/local/lib/python3.11/dist-packages/itchat_uos-1.5.0.dev0-py3.11.egg/itchat/components/login.py", line 152, in check_login
  File "/usr/local/lib/python3.11/dist-packages/itchat_uos-1.5.0.dev0-py3.11.egg/itchat/components/login.py", line 197, in process_login_info
IndexError: list index out of range
```

您的itchat版本为：`[在这里填写版本号]`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

> [您的内容]

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by josephmax** [comment]
我打印了一下报错行，返回地址显示目标账号没有开通微信支付
