### ISSUE TITLE
登录报错，KeyError: wxsid

### ISSUE THREAD

**Issue by FrankSFLYS** [why2lyj/ItChat-UOS#7]
在提交前，请确保您已经检查了以下内容!

- [ ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [ ] 我已经阅读并按[文档][document] 中的指引进行了操作
- [x] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [x] 本问题确实关于`itchat`, 而不是其他项目.
- [ ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

> 无法运行到这一步
```
[在这里粘贴完整日志]
```

您的itchat版本为：`1.4.1`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

报错内容：
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/itchat/components/login.py", line 55, in login
    status = self.check_login()
  File "/usr/local/lib/python3.8/dist-packages/itchat/components/login.py", line 141, in check_login
    if process_login_info(self, r.text):
  File "/usr/local/lib/python3.8/dist-packages/itchat/components/login.py", line 183, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'
```

[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by bydreamxxx** [comment]
同样的错误 是不是微信已经升级了？

**Comment by bydreamxxx** [comment]
确认了微信的uos已经升级了 但是改了版本号无效
https://aur.archlinux.org/cgit/aur.git/?h=wechat-uos

**Comment by heyiWF** [comment]
同问题，uos版微信更新了，这个是不是以后都用不了了啊？

**Comment by pick7** [comment]
一样的问题，一夜之前全部GG

**Comment by cupen** [comment]
同样的问题。
```
Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Traceback (most recent call last):
  File "D:\workbench\repos\aha\main.py", line 3, in <module>
    itchat.auto_login()
  File "D:\Program Files\Python310\lib\site-packages\itchat\components\register.py", line 35, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "D:\Program Files\Python310\lib\site-packages\itchat\components\login.py", line 55, in login
    status = self.check_login()
  File "D:\Program Files\Python310\lib\site-packages\itchat\components\login.py", line 141, in check_login
    if process_login_info(self, r.text):
  File "D:\Program Files\Python310\lib\site-packages\itchat\components\login.py", line 183, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'
```

**Comment by GYLQ** [comment]
同样出现了这个问题o(╥﹏╥)o

**Comment by FrankSFLYS** [comment]
我现在放弃微信 Hack 了，用企业微信提供的公开接口收发消息了。
